# Generated by Django 2.2.19 on 2022-05-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220427_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
